name: Moderation for PRs

on:
  pull_request:
    paths:
      - '**/*.json'
    types:
      - opened
      - synchronize

jobs:
  moderation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install ollama

    - name: Parse the JSON file
      id: parse_json
      run: |
        python responses/scripts/plaintext.py

    - name: Moderation Check with Ollama Model
      id: moderation
      run: |
        python responses/scripts/buildPromptAndRun.py

    - name: Upload Moderation Result
      uses: actions/upload-artifact@v3
      with:
        name: moderation_result
        path: /tmp/moderation_result.txt

    - name: Comment moderation result on PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Moderation Check Completed. Below are the results:
          ```text
          ${{ steps.moderation.outputs.result }}
          ```