name: Moderation for PRs

on:
  pull_request:
    paths:
      - '**/*.json'
    types:
      - reopened
      - opened
      - synchronize

jobs:
  moderation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
      shell: bash

    - name: Install the LLM model (mistral)
      run: |
        ollama pull mistral
      shell: bash

    - name: Build Prompt
      id: prompt
      run: |
        prompt=$(python responses/scripts/buildPrompt.py)
        echo "Prompt generated: $prompt"
        echo "::set-output name=prompt::$prompt"
      shell: bash

    - name: Run Ollama and get result
      id: ollama
      run: |
        # Get the prompt generated in the Build Prompt step
        prompt="${{ steps.prompt.outputs.prompt }}"
        
        # Call Ollama API with the prompt
        review_result=$(curl -s http://127.0.0.1:11434/api/generate \
          -d '{"model": "mistral", "prompt": "'"$prompt"'", "stream": false}' | jq -r '.response')
        
        # Set the review result as an output for later use
        echo "::set-output name=result::$review_result"
      shell: bash

    - name: Comment moderation result on PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Moderation Check Completed. Below are the results:
          ```text
          ${{ steps.ollama.outputs.result }}
          ```