name: Moderation for PRs

on:
  pull_request:
    paths:
      - '**/*.json'
    types:
      - reopened
      - opened
      - synchronize

jobs:
  moderation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
      shell: bash

    - name: Install the LLM model (mistral)
      run: |
        ollama pull mistral
      shell: bash

    - name: Build Prompt
      id: prompt
      run: |
        prompt=$(python responses/scripts/buildPrompt.py)
        echo "Prompt generated: $prompt"
        echo "::set-output name=prompt::$prompt"
      shell: bash

    - name: Run Ollama and get result
      id: ollama
      run: |
        # Get the prompt generated in the Build Prompt step
        prompt="${{ steps.prompt.outputs.prompt }}"
        
        # Call Ollama API with the prompt
        review_result=$(curl -s http://127.0.0.1:11434/api/generate \
          -d '{"model": "mistral", "prompt": "'"$prompt"'", "stream": false}' | jq -r '.response')
        
        # Set the review result as an output for later use
        echo "::set-output name=result::$review_result"
      shell: bash

    - name: Parse Ollama Result
      id: parse-result
      run: |
        parsed_result=$(echo "${{ steps.ollama.outputs.result }}" | python responses/scripts/parseOllamaOutput.py)

        can_automerge=$(echo "$parsed_result" | jq -r '.can_automerge')
        comment=$(echo "$parsed_result" | jq -r '.comment')
        
        echo "::set-output name=can_automerge::$can_automerge"
        echo "::set-output name=comment::$parsed_result"
      shell: bash
    
    - name: Comment and Automerge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ "${{ steps.parse-result.outputs.can_automerge }}" == "true" ]]; then
          gh pr merge ${{ github.event.pull_request.number }} --auto
        else
          echo "PR could not be automerged."
        fi
        gh pr comment --body "${{ steps.parse-result.outputs.comment }}"
      shell: bash