name: Moderation for PRs

on:
  pull_request:
    paths:
      - '**/*.json'
    types:
      - reopened
      - opened
      - synchronize

jobs:
  moderation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
          token: ${{ secrets.PAT }}
    
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
      shell: bash

    - name: Install the LLM model (mistral)
      run: |
        ollama pull mistral
      shell: bash

    - name: Build Prompt
      id: prompt
      run: |
        prompt=$(python responses/scripts/buildPrompt.py)
        echo "Prompt generated: $prompt"
        echo "::set-output name=prompt::$prompt"
      shell: bash

    - name: Run Ollama and get result
      id: ollama
      run: |
        # Get the prompt generated in the Build Prompt step
        prompt="${{ steps.prompt.outputs.prompt }}"
        
        # Call Ollama API with the prompt
        review_result=$(curl -s http://127.0.0.1:11434/api/generate \
          -d '{"model": "mistral", "prompt": "'"$prompt"'", "stream": false}' | jq -r '.response')
        
        # Set the review result as an output for later use
        echo "::set-output name=result::$review_result"
      shell: bash

    - name: Comment moderation result on PR and handle merge
      id: comment
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        result="${{ steps.ollama.outputs.result }}"
        result_lower=$(echo "$result" | tr '[:upper:]' '[:lower:]')

        if [[ "$result_lower" == "yes"* ]]; then
          reasoning=$(echo "$result" | sed -n 's/^Yes\. Reasoning: \(.*\)$/\1/p')
          if [[ -z "$reasoning" ]]; then
            reasoning="No specific reasoning provided."
          fi
          comment="Pull request can be automerged. Reasoning: $reasoning"
          echo "::set-output name=can-merge::true"
          gh pr merge ${{ github.event.pull_request.number }} --auto
        else
          reasoning=$(echo "$result" | sed -n 's/^No\. Reasoning: \(.*\)$/\1/p')
          if [[ -z "$reasoning" ]]; then
            reasoning="No specific reasoning provided."
          fi
          comment="Pull request could not be automerged. Reasoning: $reasoning"
          echo "::set-output name=can-merge::false"
        fi
        gh pr comment ${{ github.event.pull_request.number }} --body "$comment"

      shell: bash